## WEBSITE DESCRIPTION

title: Felipe A. Moreno
description: You can use all this information for your things :)
             Don't dudes on follow me on github and other social networks.
baseurl: "" # the subpath of your site, e.g. /blog

## PERMANENT LINK OF POSTS

#permalink: /blog/:categories/:year/:month/:day/:title
permalink: /:categories/:title

show_downloads: true

## MAIN URL

url: "http://www.jenazads.com/"

## ANALYTICS ID

google_analytics:

# BUILD SETTINGS

markdown: kramdown
theme: jekyll-theme-cayman-blog
#plugins:
#  - jekyll-feed
#exclude:
#  - Gem/Gemfile
#  - Gem/Gemfile.lock
